java -jar BerkeleyParser_KorV2.jar "그거에 "
java -jar BerkeleyParser_KorV2.jar "저는 했어야 돼요 "
java -jar BerkeleyParser_KorV2.jar "저는 이름이 뭐야 "
java -jar BerkeleyParser_KorV2.jar "유가 만들었어요 "
java -jar BerkeleyParser_KorV2.jar "너는 어떻게 말해 "
java -jar BerkeleyParser_KorV2.jar "오늘 기분 없대 "
java -jar BerkeleyParser_KorV2.jar "바람에 들어 "
java -jar BerkeleyParser_KorV2.jar "오늘 날씨는 없어요 "
java -jar BerkeleyParser_KorV2.jar "아침에는 해가 떠 "
java -jar BerkeleyParser_KorV2.jar "구르미 내용이죠 "
java -jar BerkeleyParser_KorV2.jar "비는 네 오는거요 "
java -jar BerkeleyParser_KorV2.jar "왜 겨울이 추워 "
java -jar BerkeleyParser_KorV2.jar "왜 여름에 더 "
java -jar BerkeleyParser_KorV2.jar "전등이 치면 왜 소리가 나 "
java -jar BerkeleyParser_KorV2.jar "그러면 왜 생겨 "
java -jar BerkeleyParser_KorV2.jar "문의 왜 내려 "
java -jar BerkeleyParser_KorV2.jar "왜 는 Q. 때와 "
java -jar BerkeleyParser_KorV2.jar "머문 몇 떠요 "
java -jar BerkeleyParser_KorV2.jar "왜 또는 제가 나 "
java -jar BerkeleyParser_KorV2.jar "왜 곡물이 나와요 "
java -jar BerkeleyParser_KorV2.jar "왜 폐해가 파이 요 "
java -jar BerkeleyParser_KorV2.jar "왜 근거가 나와요 "
java -jar BerkeleyParser_KorV2.jar "왜 답을 먹어요 "
java -jar BerkeleyParser_KorV2.jar "보증인 왜 사는 거에요 "
java -jar BerkeleyParser_KorV2.jar "왜 이를 작가의 "
java -jar BerkeleyParser_KorV2.jar "왜 있는 제가 나 "
java -jar BerkeleyParser_KorV2.jar "우리카드 왜 네 제가 나 "
java -jar BerkeleyParser_KorV2.jar "인터뷰에 잘라 "
java -jar BerkeleyParser_KorV2.jar "촉진해 왜 빨라 "
java -jar BerkeleyParser_KorV2.jar "셰어드 왜 뭐라도 없어 "
java -jar BerkeleyParser_KorV2.jar "잘 지금 무슨 소리를 내지 "
java -jar BerkeleyParser_KorV2.jar "왜 강아지는 말을 못해 "
java -jar BerkeleyParser_KorV2.jar "물고기는 왜 잘못 하는데 "
java -jar BerkeleyParser_KorV2.jar "컴 보기는 왼쪽이요 "
java -jar BerkeleyParser_KorV2.jar "누가 더 빨라 "
java -jar BerkeleyParser_KorV2.jar "납입한 거기 있어 "
java -jar BerkeleyParser_KorV2.jar "컴퓨터는 왜 불이 있어요 "
java -jar BerkeleyParser_KorV2.jar "땡땡이가 영화가 뭐야 "
java -jar BerkeleyParser_KorV2.jar "멘트입니다 중국어로 뭐야 "
java -jar BerkeleyParser_KorV2.jar "땡땡이가 일번으로 뭐야 "
java -jar BerkeleyParser_KorV2.jar "여기서는 뭐 하는 사람이 "
java -jar BerkeleyParser_KorV2.jar "변호사는 보안 사용하면 "
java -jar BerkeleyParser_KorV2.jar "병원 사는 뭐 해 "
java -jar BerkeleyParser_KorV2.jar "네 없는거야 "
java -jar BerkeleyParser_KorV2.jar "왜 기분이 안 좋아 "
java -jar BerkeleyParser_KorV2.jar "왜 눈물이 나와 "
java -jar BerkeleyParser_KorV2.jar "왜 화가 나 "
java -jar BerkeleyParser_KorV2.jar "돌은 업데이트 생겨 "
java -jar BerkeleyParser_KorV2.jar "그면 어떻게 되는데요 "
java -jar BerkeleyParser_KorV2.jar "받았는 어떻게 생겨 "
java -jar BerkeleyParser_KorV2.jar "포트는 이제 P. 있는거에요 "
java -jar BerkeleyParser_KorV2.jar "장비는 왜 빨간색이 요 "
java -jar BerkeleyParser_KorV2.jar "네 바닷물에 입니다 "
java -jar BerkeleyParser_KorV2.jar "다른 왜 슬러 "
java -jar BerkeleyParser_KorV2.jar "나무는 왜 커 "
java -jar BerkeleyParser_KorV2.jar "고치는 왜 뭐에요 "
java -jar BerkeleyParser_KorV2.jar "P. C.는 파일은 뭐야 "
java -jar BerkeleyParser_KorV2.jar "상관은 왜 달아 "
java -jar BerkeleyParser_KorV2.jar "탄식이 뭐야 "
java -jar BerkeleyParser_KorV2.jar "왜 살인자 "
java -jar BerkeleyParser_KorV2.jar "네 살이 빠져 "
java -jar BerkeleyParser_KorV2.jar "축구 규칙이 뭐야 "
java -jar BerkeleyParser_KorV2.jar "축구선수 명령에 "
java -jar BerkeleyParser_KorV2.jar "원구성 주면은요 "
java -jar BerkeleyParser_KorV2.jar "M. S. T. 뭐야 "
java -jar BerkeleyParser_KorV2.jar "서울이 뭐야 "
java -jar BerkeleyParser_KorV2.jar "어제 웨이버 "
java -jar BerkeleyParser_KorV2.jar "방문하시게 감정을 이거 "
java -jar BerkeleyParser_KorV2.jar "돈을 벌어 "
java -jar BerkeleyParser_KorV2.jar "돈을 왜 할게요 "
java -jar BerkeleyParser_KorV2.jar "M. 때는 얼마에요 "
java -jar BerkeleyParser_KorV2.jar "M. 때는 예 필사 "
java -jar BerkeleyParser_KorV2.jar "네 때는 어떻게 사 "
java -jar BerkeleyParser_KorV2.jar "은행은 뭐예요 "
java -jar BerkeleyParser_KorV2.jar "여기 쓰던거거든요 "
java -jar BerkeleyParser_KorV2.jar "M. 때에는 어디에 있어요 "
java -jar BerkeleyParser_KorV2.jar "왜 정도 해 "
java -jar BerkeleyParser_KorV2.jar "네 빨래 "
java -jar BerkeleyParser_KorV2.jar "왜 차원의 "
java -jar BerkeleyParser_KorV2.jar "왜 참사 "
java -jar BerkeleyParser_KorV2.jar "네 쓰레기는 버려요 "
java -jar BerkeleyParser_KorV2.jar "왜 설레는 다리가 많아요 "
java -jar BerkeleyParser_KorV2.jar "이거 파기를 "
java -jar BerkeleyParser_KorV2.jar "오는 I. C. R. 되죠 "
java -jar BerkeleyParser_KorV2.jar "우리는 왜 정면에 "
java -jar BerkeleyParser_KorV2.jar "나오는데 자라 "
java -jar BerkeleyParser_KorV2.jar "기능에 거죠 "
java -jar BerkeleyParser_KorV2.jar "공인 어떻게 많은데요 "
java -jar BerkeleyParser_KorV2.jar "그래서 왜 나라 "
java -jar BerkeleyParser_KorV2.jar "자동차상해 빨라 "
java -jar BerkeleyParser_KorV2.jar "약을 왜 뭐가 "
java -jar BerkeleyParser_KorV2.jar "네 툴이나 "
java -jar BerkeleyParser_KorV2.jar "오늘 "
java -jar BerkeleyParser_KorV2.jar "P. C.는 어디에서 여기 "
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 빠른 게 뭐야 "
java -jar BerkeleyParser_KorV2.jar "세상에서 제일 제일 큰게 뭐야 "
java -jar BerkeleyParser_KorV2.jar "세상에서 제일 로그온 게 뭐야 "
java -jar BerkeleyParser_KorV2.jar "왜 밝히는 불러 가요 "
java -jar BerkeleyParser_KorV2.jar "플랜 그런데 떠요 "
java -jar BerkeleyParser_KorV2.jar "아기는 어떻게 되었나요 "
java -jar BerkeleyParser_KorV2.jar "인생이 뭘까 "
