java -jar BerkeleyParser_KorV2.jar "Korean"
java -jar BerkeleyParser_KorV2.jar "판다는 왜 눈주위가 검은색이에요"
java -jar BerkeleyParser_KorV2.jar "비행기는 어떻게 하늘을 날아요"
java -jar BerkeleyParser_KorV2.jar "매미는 왜 울어요"
java -jar BerkeleyParser_KorV2.jar "바퀴는 왜 동그라미에요"
java -jar BerkeleyParser_KorV2.jar "개미는 왜 발이 더 많아요"
java -jar BerkeleyParser_KorV2.jar "사람은 왜 물에 떠요"
java -jar BerkeleyParser_KorV2.jar "여기에서 집에 어떻게 가요"
java -jar BerkeleyParser_KorV2.jar "엄마는 왜 머리가 길어요"
java -jar BerkeleyParser_KorV2.jar "외국인은 왜 눈동자색이 달라요"
java -jar BerkeleyParser_KorV2.jar "밤이 되면 왜 어두워져요"
java -jar BerkeleyParser_KorV2.jar "눈은 왜 때려요"
java -jar BerkeleyParser_KorV2.jar "비는 어떻게 내려요"
java -jar BerkeleyParser_KorV2.jar "강아지는 사람 말을 알아 들어요"
java -jar BerkeleyParser_KorV2.jar "계절이 있는 이유가 뭐예요"
java -jar BerkeleyParser_KorV2.jar "하늘은 색은 왜 변해요"
java -jar BerkeleyParser_KorV2.jar "손톱은 왜 잘 안"
java -jar BerkeleyParser_KorV2.jar "비둘기는 뭘 먹어요"
java -jar BerkeleyParser_KorV2.jar "왜 사람마다 얼굴이 달라요"
java -jar BerkeleyParser_KorV2.jar "키는 언제 자라요"
java -jar BerkeleyParser_KorV2.jar "왜 내 친구는 키가 나보다 커요"
java -jar BerkeleyParser_KorV2.jar "너는 왜 나빠져요"
java -jar BerkeleyParser_KorV2.jar "안경은 왜 써요"
java -jar BerkeleyParser_KorV2.jar "솜사탕은 어떻게 만들어요"
java -jar BerkeleyParser_KorV2.jar "헬륨풍선은 왜 하늘에 떠요"
java -jar BerkeleyParser_KorV2.jar "바닷물은 왜 마시면 안 돼요"
java -jar BerkeleyParser_KorV2.jar "비는 왜 내려요"
java -jar BerkeleyParser_KorV2.jar "낙엽은 왜 떨어져요"
java -jar BerkeleyParser_KorV2.jar "가을에는 위에 나무가 빨개 져요"
java -jar BerkeleyParser_KorV2.jar "북극곰은 안 추워요"
java -jar BerkeleyParser_KorV2.jar "여름에 강아지는 안 더워요"
java -jar BerkeleyParser_KorV2.jar "왜 단 거는 몸에 안 좋아요"
java -jar BerkeleyParser_KorV2.jar "라면 어떻게 끓여요"
java -jar BerkeleyParser_KorV2.jar "물은 왜 투명 해요"
java -jar BerkeleyParser_KorV2.jar "불은 왜 뜨거워요"
java -jar BerkeleyParser_KorV2.jar "모기는 왜 사람을 물어요"
java -jar BerkeleyParser_KorV2.jar "구름은 왜 움직여요"
java -jar BerkeleyParser_KorV2.jar "그룹은 왜 하얀색이에요"
java -jar BerkeleyParser_KorV2.jar "아빠는 왜 맨날 똑같은 옷만 입어요"
java -jar BerkeleyParser_KorV2.jar "아빠는 왜 맨날 늦게 들어와요"
java -jar BerkeleyParser_KorV2.jar "산타할아버지가 진짜 있어요"
java -jar BerkeleyParser_KorV2.jar "왜 크리스마스에 양말을 걸어요"
java -jar BerkeleyParser_KorV2.jar "생일에는 왜 케익을 먹어요"
java -jar BerkeleyParser_KorV2.jar "설날에는 왜 떡국을 먹어요"
java -jar BerkeleyParser_KorV2.jar "학교에는 왜 가야 하나요"
java -jar BerkeleyParser_KorV2.jar "배는 왜 바다에 떠"
java -jar BerkeleyParser_KorV2.jar "버스는 왜 이리 커요"
java -jar BerkeleyParser_KorV2.jar "지우개는 어떻게 글자를"
java -jar BerkeleyParser_KorV2.jar "달 그 왜 날개가 있는데 못 날아요"
java -jar BerkeleyParser_KorV2.jar "채소는 왜 맛이 없어요"
java -jar BerkeleyParser_KorV2.jar "취소는 왜 초록색이에요"
java -jar BerkeleyParser_KorV2.jar "커피는 왜 마셔요"
java -jar BerkeleyParser_KorV2.jar "담배는 왜 펴요"
java -jar BerkeleyParser_KorV2.jar "술은 왜 마셔요"
java -jar BerkeleyParser_KorV2.jar "교복은 왜 입어요"
java -jar BerkeleyParser_KorV2.jar "아빠는 왜 항상 피곤해요"
java -jar BerkeleyParser_KorV2.jar "놀이공원에 언제 가요"
java -jar BerkeleyParser_KorV2.jar "양치는 왜 밥 먹고 나서 해요"
java -jar BerkeleyParser_KorV2.jar "시금치는 왜 맛이 없어요"
java -jar BerkeleyParser_KorV2.jar "왜 남자들은 치마를 안 입어요"
java -jar BerkeleyParser_KorV2.jar "화장은 왜 해요"
java -jar BerkeleyParser_KorV2.jar "산에 있는 나무는 누가 물을 주나요"
java -jar BerkeleyParser_KorV2.jar "꽃은 어떻게 펴요"
java -jar BerkeleyParser_KorV2.jar "손가락 발가락은 왜 10개"
java -jar BerkeleyParser_KorV2.jar "남자랑 여자는 왜 달라요"
java -jar BerkeleyParser_KorV2.jar "임산부는 왜 배가 나와요"
java -jar BerkeleyParser_KorV2.jar "외계인 있나요"
java -jar BerkeleyParser_KorV2.jar "신이 있나요"
java -jar BerkeleyParser_KorV2.jar "감기 걸리면 왜 열이나요"
java -jar BerkeleyParser_KorV2.jar "주사를 맞으면 왜 빨리 나아"
java -jar BerkeleyParser_KorV2.jar "기침은 왜 나와요"
java -jar BerkeleyParser_KorV2.jar "사마귀는 왜 물이 없어요"
java -jar BerkeleyParser_KorV2.jar "사막에서 선인장은 어떻게 살아"
java -jar BerkeleyParser_KorV2.jar "얼음은 어떻게 알아요"
java -jar BerkeleyParser_KorV2.jar "바다에서 누가 왕이에요"
java -jar BerkeleyParser_KorV2.jar "사자랑 호랑이 중에 누가 써요"
java -jar BerkeleyParser_KorV2.jar "춤추는 왜 생겨요"
java -jar BerkeleyParser_KorV2.jar "무지개는 어떻게 생겨요"
java -jar BerkeleyParser_KorV2.jar "안개는 왜 생겨요"
java -jar BerkeleyParser_KorV2.jar "배가 고프면 왜 소리가 나"
java -jar BerkeleyParser_KorV2.jar "두 사람은 왜 녹아요"
java -jar BerkeleyParser_KorV2.jar "풍선은 왜 터져요"
java -jar BerkeleyParser_KorV2.jar "분리수거는 왜 하는 거예요"
java -jar BerkeleyParser_KorV2.jar "하품을 하면 왜 눈물이나요"
java -jar BerkeleyParser_KorV2.jar "번개장터 똥은 왜 치나요"
java -jar BerkeleyParser_KorV2.jar "왜 은행에 돈을 맡겨요"
java -jar BerkeleyParser_KorV2.jar "얼음은 왜 차가워요"
java -jar BerkeleyParser_KorV2.jar "여순 왜 입에 달라붙어요"
java -jar BerkeleyParser_KorV2.jar "제사는 왜 지내요"
java -jar BerkeleyParser_KorV2.jar "양주는 왜 녹아요"
java -jar BerkeleyParser_KorV2.jar "사람들은 왜 카페에 가요"
java -jar BerkeleyParser_KorV2.jar "바다는 왜 안얼어요"
java -jar BerkeleyParser_KorV2.jar "왜 제주도는 더 따뜻해요"
java -jar BerkeleyParser_KorV2.jar "거북이는 왜 느려요"
java -jar BerkeleyParser_KorV2.jar "걔는 왜 옆으로 걸어요"
java -jar BerkeleyParser_KorV2.jar "햄버거는 왜 자주 먹으면 안돼요"
java -jar BerkeleyParser_KorV2.jar "왜 나라마다 쓰는 언어가 달라요"
java -jar BerkeleyParser_KorV2.jar "월드컵은 왜 4년마다 열려요"
java -jar BerkeleyParser_KorV2.jar "물고기는 어떻게 숨을 쉬어요"
java -jar BerkeleyParser_KorV2.jar "종이는 왜 하얀색이에요"
java -jar BerkeleyParser_KorV2.jar "때는 왜 밀어"
java -jar BerkeleyParser_KorV2.jar "미세먼지는 왜 생겨"
