java -jar BerkeleyParser_KorV2.jar "몇 살이야"
java -jar BerkeleyParser_KorV2.jar "너는 이름이 뭐야"
java -jar BerkeleyParser_KorV2.jar "누가 만들었어"
java -jar BerkeleyParser_KorV2.jar "어떻게 말해"
java -jar BerkeleyParser_KorV2.jar "오늘 기분 어때"
java -jar BerkeleyParser_KorV2.jar "바람은 왜 불어"
java -jar BerkeleyParser_KorV2.jar "오늘 날씨 몇 도야"
java -jar BerkeleyParser_KorV2.jar "아침 해가 떠"
java -jar BerkeleyParser_KorV2.jar "구름이 왜 움직여"
java -jar BerkeleyParser_KorV2.jar "비는 왜 오는 거야"
java -jar BerkeleyParser_KorV2.jar "겨울이 추워"
java -jar BerkeleyParser_KorV2.jar "여름이 더워"
java -jar BerkeleyParser_KorV2.jar "선생님이 왜 소리가 나"
java -jar BerkeleyParser_KorV2.jar "구름이 왜 생겨"
java -jar BerkeleyParser_KorV2.jar "왠 일이야"
java -jar BerkeleyParser_KorV2.jar "애들 추울 때 와"
java -jar BerkeleyParser_KorV2.jar "몇 도야"
java -jar BerkeleyParser_KorV2.jar "똥 냄새가 나"
java -jar BerkeleyParser_KorV2.jar "콧물이 나와요"
java -jar BerkeleyParser_KorV2.jar "비가 와요"
java -jar BerkeleyParser_KorV2.jar "응가가 나와요"
java -jar BerkeleyParser_KorV2.jar "예 밥을 먹어요"
java -jar BerkeleyParser_KorV2.jar "오징어 몇 사는 거야"
java -jar BerkeleyParser_KorV2.jar "왜 이래 닦아야 해"
java -jar BerkeleyParser_KorV2.jar "있는지 가나"
java -jar BerkeleyParser_KorV2.jar "머리카락은 왜 나와"
java -jar BerkeleyParser_KorV2.jar "W 자라"
java -jar BerkeleyParser_KorV2.jar "토끼는 왜 빨라"
java -jar BerkeleyParser_KorV2.jar "쇠비듬 아 왜 꺼 부러졌어"
java -jar BerkeleyParser_KorV2.jar "무슨 소리를 내지"
java -jar BerkeleyParser_KorV2.jar "다 가지는 말하면 돼"
java -jar BerkeleyParser_KorV2.jar "거기 되면 잠을 안 자"
java -jar BerkeleyParser_KorV2.jar "거북이는 왜 이래"
java -jar BerkeleyParser_KorV2.jar "누가 더 빨라"
java -jar BerkeleyParser_KorV2.jar "나탈리 후기 있어"
java -jar BerkeleyParser_KorV2.jar "커피스토리 있어"
java -jar BerkeleyParser_KorV2.jar "여기가 영어로 뭐야"
java -jar BerkeleyParser_KorV2.jar "저기가 중국어로 뭐야"
java -jar BerkeleyParser_KorV2.jar "어디가 일본어로 뭐야"
java -jar BerkeleyParser_KorV2.jar "의사는 뭐 하는 사람이야"
java -jar BerkeleyParser_KorV2.jar "되는 사람 뭐 하는 사람이야"
java -jar BerkeleyParser_KorV2.jar "장사는 뭐 해"
java -jar BerkeleyParser_KorV2.jar "왜 웃는 거야"
java -jar BerkeleyParser_KorV2.jar "왜 기분이 안 좋아"
java -jar BerkeleyParser_KorV2.jar "물이 나와"
java -jar BerkeleyParser_KorV2.jar "왜 화가 나"
java -jar BerkeleyParser_KorV2.jar "돌 어떻게 생겨"
java -jar BerkeleyParser_KorV2.jar "아기는 어떻게 생겨"
java -jar BerkeleyParser_KorV2.jar "바다는 어떻게 생겨"
java -jar BerkeleyParser_KorV2.jar "거지 만들기"
java -jar BerkeleyParser_KorV2.jar "장미는 왜 빨간색이야"
java -jar BerkeleyParser_KorV2.jar "바닷물 한자"
java -jar BerkeleyParser_KorV2.jar "나는 왜 몰라"
java -jar BerkeleyParser_KorV2.jar "나무는 왜 꺼"
java -jar BerkeleyParser_KorV2.jar "고추는 왜 매워"
java -jar BerkeleyParser_KorV2.jar "메모는 왜 쉬어"
java -jar BerkeleyParser_KorV2.jar "신가 이름 뭐야"
java -jar BerkeleyParser_KorV2.jar "왜 자라"
java -jar BerkeleyParser_KorV2.jar "음식이 뭐야"
java -jar BerkeleyParser_KorV2.jar "왜 살이 쪄"
java -jar BerkeleyParser_KorV2.jar "왜 살이 빠져"
java -jar BerkeleyParser_KorV2.jar "끌어치기"
java -jar BerkeleyParser_KorV2.jar "디스크 수술 몇 명이야"
java -jar BerkeleyParser_KorV2.jar "선생님 몇 명이야"
java -jar BerkeleyParser_KorV2.jar "위스키 치기 뭐야"
java -jar BerkeleyParser_KorV2.jar "그리고"
java -jar BerkeleyParser_KorV2.jar ""
java -jar BerkeleyParser_KorV2.jar "장례식에 왜 검정 옷을 입어"
java -jar BerkeleyParser_KorV2.jar ""
java -jar BerkeleyParser_KorV2.jar "왜 학교"
java -jar BerkeleyParser_KorV2.jar "얼마야"
java -jar BerkeleyParser_KorV2.jar ""
java -jar BerkeleyParser_KorV2.jar "제사"
java -jar BerkeleyParser_KorV2.jar "니는 뭐 해"
java -jar BerkeleyParser_KorV2.jar "수도가 어디야"
java -jar BerkeleyParser_KorV2.jar "은 어디에 있어"
java -jar BerkeleyParser_KorV2.jar ""
java -jar BerkeleyParser_KorV2.jar "빨리"
java -jar BerkeleyParser_KorV2.jar ""
java -jar BerkeleyParser_KorV2.jar "잠자"
java -jar BerkeleyParser_KorV2.jar "쓰레기를 버려"
java -jar BerkeleyParser_KorV2.jar "걸려있는 다리가 많아요"
java -jar BerkeleyParser_KorV2.jar "2 곱하기 2는"
java -jar BerkeleyParser_KorV2.jar "오늘 날씨 알려 줘"
java -jar BerkeleyParser_KorV2.jar "우리는 왜 두 명이"
java -jar BerkeleyParser_KorV2.jar "나무는 왜 자라"
java -jar BerkeleyParser_KorV2.jar "근데 왜 꺼져"
java -jar BerkeleyParser_KorV2.jar "종이는 어떻게 만들"
java -jar BerkeleyParser_KorV2.jar ""
java -jar BerkeleyParser_KorV2.jar "자동차는 빨라"
java -jar BerkeleyParser_KorV2.jar "약을 왜 먹어"
java -jar BerkeleyParser_KorV2.jar "애플이나"
java -jar BerkeleyParser_KorV2.jar "아니 왜 자다"
java -jar BerkeleyParser_KorV2.jar "어디 살지"
java -jar BerkeleyParser_KorV2.jar "생일축하 제일 빠른게 뭐야"
java -jar BerkeleyParser_KorV2.jar "제일 큰게 보였다"
java -jar BerkeleyParser_KorV2.jar "세상에서 제일 무거운게 뭐야"
java -jar BerkeleyParser_KorV2.jar "밖에는 불러야 하나요"
java -jar BerkeleyParser_KorV2.jar "그는 몇 도야"
java -jar BerkeleyParser_KorV2.jar "어디서 태연"
java -jar BerkeleyParser_KorV2.jar "인생은 뭘까"
