java -jar BerkeleyParser_KorV2.jar "Korean"
java -jar BerkeleyParser_KorV2.jar "너는 몇 살이야"
java -jar BerkeleyParser_KorV2.jar "너는 이름이 뭐야"
java -jar BerkeleyParser_KorV2.jar "누가 만들었어"
java -jar BerkeleyParser_KorV2.jar "너는 어떻게 말해"
java -jar BerkeleyParser_KorV2.jar "오늘 기분 어때"
java -jar BerkeleyParser_KorV2.jar "바람은 왜 불어"
java -jar BerkeleyParser_KorV2.jar "오늘 날씨 몇 도야"
java -jar BerkeleyParser_KorV2.jar "아침에는 왜 해가 떠"
java -jar BerkeleyParser_KorV2.jar "구름이 왜 움직여"
java -jar BerkeleyParser_KorV2.jar "비는 왜 오는 거야"
java -jar BerkeleyParser_KorV2.jar "왜 겨울이 추워"
java -jar BerkeleyParser_KorV2.jar "왜 여름에 더워"
java -jar BerkeleyParser_KorV2.jar "천둥이 치면 왜 소리가 나"
java -jar BerkeleyParser_KorV2.jar "구름이 왜 생겨"
java -jar BerkeleyParser_KorV2.jar "눈이 왜 내려"
java -jar BerkeleyParser_KorV2.jar "왜 너는 추울 때 와"
java -jar BerkeleyParser_KorV2.jar "몸은 몇 도야"
java -jar BerkeleyParser_KorV2.jar "왜 똥 냄새가 나"
java -jar BerkeleyParser_KorV2.jar "왜 콧물이 나와요"
java -jar BerkeleyParser_KorV2.jar "왜 배가 아파요"
java -jar BerkeleyParser_KorV2.jar "왜 응가가 나와요"
java -jar BerkeleyParser_KorV2.jar "왜 밥을 먹어요"
java -jar BerkeleyParser_KorV2.jar "왜 오줌을 싸는 거야"
java -jar BerkeleyParser_KorV2.jar "왜 이래 닦아야 해"
java -jar BerkeleyParser_KorV2.jar "왜 입 냄새가 나"
java -jar BerkeleyParser_KorV2.jar "머리카락은 왜 나"
java -jar BerkeleyParser_KorV2.jar "손톱을 왜 탈락"
java -jar BerkeleyParser_KorV2.jar "토끼는 왜 빨라"
java -jar BerkeleyParser_KorV2.jar "새우 등은 왜 꼬부라져 써"
java -jar BerkeleyParser_KorV2.jar "닭은 무슨 소리를 내지"
java -jar BerkeleyParser_KorV2.jar "왜 강아지는 말을 못 해"
java -jar BerkeleyParser_KorV2.jar "물고기는 왜 잠을 안자"
java -jar BerkeleyParser_KorV2.jar "거북이는 왜 느려"
java -jar BerkeleyParser_KorV2.jar "누가 더 빨라"
java -jar BerkeleyParser_KorV2.jar "낙타는 왜 혹이 있어"
java -jar BerkeleyParser_KorV2.jar "코뿔소는 왜 뿔이 있어"
java -jar BerkeleyParser_KorV2.jar "이게 영어로 뭐야"
java -jar BerkeleyParser_KorV2.jar "이게 중국어로 뭐야"
java -jar BerkeleyParser_KorV2.jar "이게 일본어로 뭐야"
java -jar BerkeleyParser_KorV2.jar "의사는 뭐 하는 사람이야"
java -jar BerkeleyParser_KorV2.jar "변호사를 뭐 하는 사람이야"
java -jar BerkeleyParser_KorV2.jar "정원사는 뭐 해"
java -jar BerkeleyParser_KorV2.jar "왜 웃는 거야"
java -jar BerkeleyParser_KorV2.jar "왜 기분이 안 좋아"
java -jar BerkeleyParser_KorV2.jar "왜 눈물이 나와"
java -jar BerkeleyParser_KorV2.jar "왜 화가 나"
java -jar BerkeleyParser_KorV2.jar "돌은 어떻게 생겨"
java -jar BerkeleyParser_KorV2.jar "흙은 어떻게 생겨"
java -jar BerkeleyParser_KorV2.jar "바다는 어떻게 생겨"
java -jar BerkeleyParser_KorV2.jar "꽃은 언제 피는 거야"
java -jar BerkeleyParser_KorV2.jar "장미는 왜 빨간색이야"
java -jar BerkeleyParser_KorV2.jar "왜 바닷물은 자"
java -jar BerkeleyParser_KorV2.jar "강은 왜 흘러"
java -jar BerkeleyParser_KorV2.jar "남원은 왜 커"
java -jar BerkeleyParser_KorV2.jar "고추는 왜 매워"
java -jar BerkeleyParser_KorV2.jar "4번은 왜 샤워"
java -jar BerkeleyParser_KorV2.jar "신과 이름 뭐야"
java -jar BerkeleyParser_KorV2.jar "사과는 왜 달아"
java -jar BerkeleyParser_KorV2.jar "단 음식이 뭐야"
java -jar BerkeleyParser_KorV2.jar "왜 살이 쪄"
java -jar BerkeleyParser_KorV2.jar "왜 살이 빠져"
java -jar BerkeleyParser_KorV2.jar "축구규칙이 뭐야"
java -jar BerkeleyParser_KorV2.jar "축구 선수는 몇 명이야"
java -jar BerkeleyParser_KorV2.jar "농구 선수는 몇 명이야"
java -jar BerkeleyParser_KorV2.jar "테니스 규칙이 뭐야"
java -jar BerkeleyParser_KorV2.jar "파오리 뭐야"
java -jar BerkeleyParser_KorV2.jar "옷은 왜 입어"
java -jar BerkeleyParser_KorV2.jar "장례식에 왜 검정 옷 입어"
java -jar BerkeleyParser_KorV2.jar "돈을 왜 벌어"
java -jar BerkeleyParser_KorV2.jar "돈을 왜 학교"
java -jar BerkeleyParser_KorV2.jar "이거는 얼마야"
java -jar BerkeleyParser_KorV2.jar "이거는 왜 비싸"
java -jar BerkeleyParser_KorV2.jar "이거는 어떻게 사"
java -jar BerkeleyParser_KorV2.jar "은행은 뭐 해"
java -jar BerkeleyParser_KorV2.jar "여기 수도가 어디야"
java -jar BerkeleyParser_KorV2.jar "여기는 어디에 있어"
java -jar BerkeleyParser_KorV2.jar "왜 청소해"
java -jar BerkeleyParser_KorV2.jar "왜 빨래해"
java -jar BerkeleyParser_KorV2.jar "왜 샤워해"
java -jar BerkeleyParser_KorV2.jar "오늘 잠자"
java -jar BerkeleyParser_KorV2.jar "왜 쓰레기를 버려"
java -jar BerkeleyParser_KorV2.jar "왜 벌레는 다리가 많아요"
java -jar BerkeleyParser_KorV2.jar "2 곱하기 2는"
java -jar BerkeleyParser_KorV2.jar "오늘 날씨 알려 줘"
java -jar BerkeleyParser_KorV2.jar "유리는 왜 투명 해"
java -jar BerkeleyParser_KorV2.jar "나무는 왜 자라"
java -jar BerkeleyParser_KorV2.jar "키는 왜 꺼져"
java -jar BerkeleyParser_KorV2.jar "종이는 어떻게 만들어"
java -jar BerkeleyParser_KorV2.jar "로켓은 왜 나라"
java -jar BerkeleyParser_KorV2.jar "자동차는 왜 빨라"
java -jar BerkeleyParser_KorV2.jar "약을 왜 먹어"
java -jar BerkeleyParser_KorV2.jar "왜 부리다"
java -jar BerkeleyParser_KorV2.jar "문을 왜 닫아"
java -jar BerkeleyParser_KorV2.jar "지진은 어디에서 알지"
java -jar BerkeleyParser_KorV2.jar "세상에서 제일 빠른게 뭐야"
java -jar BerkeleyParser_KorV2.jar "세상에서 제일 큰게 뭐야"
java -jar BerkeleyParser_KorV2.jar "세상에서 제일 무거운게 뭐야"
java -jar BerkeleyParser_KorV2.jar "왜 바뀌는 굴러가요"
java -jar BerkeleyParser_KorV2.jar "끓는 물은 몇 도야"
java -jar BerkeleyParser_KorV2.jar "아기는 어디서 태어나"
java -jar BerkeleyParser_KorV2.jar "인생이 볼까"
