java -jar BerkeleyParser_KorV2.jar "왜 공룡은 멸종 됐나요"
java -jar BerkeleyParser_KorV2.jar "내 사랑은 아픈가요"
java -jar BerkeleyParser_KorV2.jar "1 더하기 1은 2"
java -jar BerkeleyParser_KorV2.jar "나는 무엇으로 만들어졌나요"
java -jar BerkeleyParser_KorV2.jar "사람의 - 쓰는 몇 개인가요"
java -jar BerkeleyParser_KorV2.jar "왜 밤은 어디 있나요"
java -jar BerkeleyParser_KorV2.jar "왜 바다는 짜요"
java -jar BerkeleyParser_KorV2.jar "손톱은 한달에 얼마나 살아요"
java -jar BerkeleyParser_KorV2.jar "머리는 한달에 얼마나 살아요"
java -jar BerkeleyParser_KorV2.jar "사람의 머리에는 몇 개의 머리카락이 있나요"
java -jar BerkeleyParser_KorV2.jar "언니"
java -jar BerkeleyParser_KorV2.jar "지금 몇 시예요"
java -jar BerkeleyParser_KorV2.jar "오늘의 날씨가 어때요"
java -jar BerkeleyParser_KorV2.jar "오늘은 몇일인가요"
java -jar BerkeleyParser_KorV2.jar "너의 이름은 뭐야"
java -jar BerkeleyParser_KorV2.jar "넌 몇 살이야"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 오래 사는 동물은"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 이빨이 많은 동물은"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 빠른 동물은"
java -jar BerkeleyParser_KorV2.jar "누가 TV를 발명했나요"
java -jar BerkeleyParser_KorV2.jar "한국의 최초 대통령 이름"
java -jar BerkeleyParser_KorV2.jar "1 달러는 몇 원인가요"
java -jar BerkeleyParser_KorV2.jar "세상에서 제일 큰 산은"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 큰 바다는"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 큰 나라는"
java -jar BerkeleyParser_KorV2.jar "지구의 둘레는"
java -jar BerkeleyParser_KorV2.jar "미국의 수도는"
java -jar BerkeleyParser_KorV2.jar "겨울왕국 주인공의 이름은"
java -jar BerkeleyParser_KorV2.jar "내 고추는 맵나요"
java -jar BerkeleyParser_KorV2.jar "해리포터가 나온 학교에 이름은"
java -jar BerkeleyParser_KorV2.jar "무지개는 무슨 색깔별로이 이루어져 있나요"
java -jar BerkeleyParser_KorV2.jar "한국에서 가장 큰 가게 이름"
java -jar BerkeleyParser_KorV2.jar "한국에서 가장 높은 산은"
java -jar BerkeleyParser_KorV2.jar "피사의 탑 있는 도시의 이름은"
java -jar BerkeleyParser_KorV2.jar "해리포터 애완 올빼미 이름은"
java -jar BerkeleyParser_KorV2.jar "1세기는 몇년인가요"
java -jar BerkeleyParser_KorV2.jar "언제 공룡이 몇 쪽 있나요"
java -jar BerkeleyParser_KorV2.jar "한국의 역사는 얼마나 길어요"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 큰 물고기는"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 빠른 물고기는"
java -jar BerkeleyParser_KorV2.jar "지구에서 달까지 달까지의 거리"
java -jar BerkeleyParser_KorV2.jar "지는 얼마나 뜨거운가"
java -jar BerkeleyParser_KorV2.jar "지구 은하계는 몇 개 행성의 존재하나요"
java -jar BerkeleyParser_KorV2.jar "나 지구의 나이는"
java -jar BerkeleyParser_KorV2.jar "지구는 어떻게 생겼나요"
java -jar BerkeleyParser_KorV2.jar "우리는 어떻게 숨을 쉬나요"
java -jar BerkeleyParser_KorV2.jar "물고기는 어떻게 숨을 쉬나요"
java -jar BerkeleyParser_KorV2.jar "고래는 얼마나 커요"
java -jar BerkeleyParser_KorV2.jar "스타는 얼마나 빨리 날리나요"
java -jar BerkeleyParser_KorV2.jar "붙이는 얼마나 빠른가요"
java -jar BerkeleyParser_KorV2.jar "공기는 어떤 물질로 되어 있나요"
java -jar BerkeleyParser_KorV2.jar "나무는 어떻게 생기나요"
java -jar BerkeleyParser_KorV2.jar "한국에서 일본까지 거리"
java -jar BerkeleyParser_KorV2.jar "한국에서 일본까지 비행기로 몇시간 걸리나요"
java -jar BerkeleyParser_KorV2.jar "한국에서 일본까지 몇 배로 몇 시간 걸리나요"
java -jar BerkeleyParser_KorV2.jar "왜 누나 하나요"
java -jar BerkeleyParser_KorV2.jar "비는 어떤 원리로 내리나요"
java -jar BerkeleyParser_KorV2.jar "비가 가장 많이 오는 나라는"
java -jar BerkeleyParser_KorV2.jar "비가 가장 조금 오는 나라는"
java -jar BerkeleyParser_KorV2.jar "번개가 치는 원리"
java -jar BerkeleyParser_KorV2.jar "천둥 소리가 생기는 이유"
java -jar BerkeleyParser_KorV2.jar "천둥 소리가 번개보다 늦게 들리는 이유"
java -jar BerkeleyParser_KorV2.jar "허리케인이 생기는 이유"
java -jar BerkeleyParser_KorV2.jar "차가 움직이는 원리"
java -jar BerkeleyParser_KorV2.jar "차가 가장 많은 나라는"
java -jar BerkeleyParser_KorV2.jar "얼음이 생기는 원리"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 더운 나라"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 추운 나라"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 큰 새는"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 빠른 새는"
java -jar BerkeleyParser_KorV2.jar "낼 수 없는 새가 있나요"
java -jar BerkeleyParser_KorV2.jar "왜 펭귄은 날 수 없나요"
java -jar BerkeleyParser_KorV2.jar "펭귄은 왜 무리지어서 사나"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 작은 동물은"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 큰 곤충은"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 큰 가장 작은 곤충은"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 강한 곤충은"
java -jar BerkeleyParser_KorV2.jar "재미가 놀 수 있는 무게는"
java -jar BerkeleyParser_KorV2.jar "사마귀 일터 계시면"
java -jar BerkeleyParser_KorV2.jar "쇠똥구리는 어떤 것들인가요"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 긴 곤충은"
java -jar BerkeleyParser_KorV2.jar "한국에서 가장 큰 도시는"
java -jar BerkeleyParser_KorV2.jar "한국의 인구 수는"
java -jar BerkeleyParser_KorV2.jar "가장 인구가 많은 나라는"
java -jar BerkeleyParser_KorV2.jar "중국 인구 수는"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 많이 쓰이는 언어는"
java -jar BerkeleyParser_KorV2.jar "판다의 주식은"
java -jar BerkeleyParser_KorV2.jar "대나무는 어떻게 자라나요"
java -jar BerkeleyParser_KorV2.jar "하나의 적은 얼마나 쓰나요"
java -jar BerkeleyParser_KorV2.jar "상어 이빨 수는"
java -jar BerkeleyParser_KorV2.jar "늑대인간은 출전하나요"
java -jar BerkeleyParser_KorV2.jar "인간의 보통 달리기 속도는"
java -jar BerkeleyParser_KorV2.jar "인간의 보통 시력은"
java -jar BerkeleyParser_KorV2.jar "가장 키가 큰 인간의 이름은"
java -jar BerkeleyParser_KorV2.jar "사람은 얼마나 사나요"
java -jar BerkeleyParser_KorV2.jar "거북이의 수명은"
java -jar BerkeleyParser_KorV2.jar "커피는 어떻게 만들어지나요"
java -jar BerkeleyParser_KorV2.jar "한국의 크기는"
java -jar BerkeleyParser_KorV2.jar "오로라는 어떻게 만들어지나요"
java -jar BerkeleyParser_KorV2.jar "월요일 날 볼 수 있는 시기는"
