java -jar BerkeleyParser_KorV2.jar "Korean"
java -jar BerkeleyParser_KorV2.jar "왜 공룡은 멸종 됐나요"
java -jar BerkeleyParser_KorV2.jar "왜 사람은 아픈가요"
java -jar BerkeleyParser_KorV2.jar "1 더하기 1은 2"
java -jar BerkeleyParser_KorV2.jar "나는 무엇으로 만들어 졌나요"
java -jar BerkeleyParser_KorV2.jar "사람의 뼈에게 쓰는 몇 개인가요"
java -jar BerkeleyParser_KorV2.jar "왜 밤은 어둡나요"
java -jar BerkeleyParser_KorV2.jar "왜 바다는 짜요"
java -jar BerkeleyParser_KorV2.jar "손톱은 한달에 얼마나 자라요"
java -jar BerkeleyParser_KorV2.jar "머리는 한달에 얼마나 자라요"
java -jar BerkeleyParser_KorV2.jar "사람 머리에는 몇 개의 머리카락이 있나요"
java -jar BerkeleyParser_KorV2.jar "안녕"
java -jar BerkeleyParser_KorV2.jar "지금 몇 시예요"
java -jar BerkeleyParser_KorV2.jar "오늘의 날씨가 어때요"
java -jar BerkeleyParser_KorV2.jar "오늘은 몇일인가요"
java -jar BerkeleyParser_KorV2.jar "너의 이름은 뭐야"
java -jar BerkeleyParser_KorV2.jar "넌 몇 살이야"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 오래 사는 동물은"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 이빨이 많은 동물은"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 빠른 동물은"
java -jar BerkeleyParser_KorV2.jar "누가 TV를 발명했나요"
java -jar BerkeleyParser_KorV2.jar "한국의 초대 대통령 이름은"
java -jar BerkeleyParser_KorV2.jar "1 달러는 몇 원인가요"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 큰 섬은"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 큰 바다는"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 큰 나라는"
java -jar BerkeleyParser_KorV2.jar "지구의 둘레는"
java -jar BerkeleyParser_KorV2.jar "미국의 수도는"
java -jar BerkeleyParser_KorV2.jar "겨울왕국 주인공은 이름은"
java -jar BerkeleyParser_KorV2.jar "왜 고추는 맵나요"
java -jar BerkeleyParser_KorV2.jar "해리포터가 나온 학교에 이름은"
java -jar BerkeleyParser_KorV2.jar "무지개는 무슨 색깔들로 이루어져 있나요"
java -jar BerkeleyParser_KorV2.jar "한국에서 가장 큰 강의 이름은"
java -jar BerkeleyParser_KorV2.jar "한국에서 가장 높은 산"
java -jar BerkeleyParser_KorV2.jar "피사의 탑 있는 도시의 이름은"
java -jar BerkeleyParser_KorV2.jar "해리포터의 애완올빼미 이름은"
java -jar BerkeleyParser_KorV2.jar "1세기는 몇년인가요"
java -jar BerkeleyParser_KorV2.jar "언제 공룡이 멸종 했나요"
java -jar BerkeleyParser_KorV2.jar "한국의 역사는 얼마나 길어요"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 큰 물고기는"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 빠른 물고기는"
java -jar BerkeleyParser_KorV2.jar "지구에서 달까지 거리"
java -jar BerkeleyParser_KorV2.jar "해 난 얼마나 뜨거운"
java -jar BerkeleyParser_KorV2.jar "지구 은하계는 몇 개 행성의 존재하다"
java -jar BerkeleyParser_KorV2.jar "지구의 나이는"
java -jar BerkeleyParser_KorV2.jar "지구는 어떻게 생겼나요"
java -jar BerkeleyParser_KorV2.jar "우리는 어떻게 숨을 쉬나요"
java -jar BerkeleyParser_KorV2.jar "물고기는 어떻게 숨을 쉬나요"
java -jar BerkeleyParser_KorV2.jar "고래는 얼마나 커요"
java -jar BerkeleyParser_KorV2.jar "재판은 얼마나 빨리 달리나요"
java -jar BerkeleyParser_KorV2.jar "도대체가 얼마나 빠른가요"
java -jar BerkeleyParser_KorV2.jar "공기는 어떤 물질로 되어 있나요"
java -jar BerkeleyParser_KorV2.jar "나무는 어떻게 생기나요"
java -jar BerkeleyParser_KorV2.jar "한국에서 일본까지 거리"
java -jar BerkeleyParser_KorV2.jar "한국에서 일본까지 비행기로 몇시간 걸리나요"
java -jar BerkeleyParser_KorV2.jar "한국에서 일본까지 배로 몇 시간 걸리나"
java -jar BerkeleyParser_KorV2.jar "왜 눈은 하였나요"
java -jar BerkeleyParser_KorV2.jar "일은 어떤 원리로 내리나요"
java -jar BerkeleyParser_KorV2.jar "비가 가장 많이 오는"
java -jar BerkeleyParser_KorV2.jar "비가 가장 조금 오는 날은"
java -jar BerkeleyParser_KorV2.jar "번개가 치는 원리"
java -jar BerkeleyParser_KorV2.jar "진동 소리가 생기는 이유"
java -jar BerkeleyParser_KorV2.jar "천둥 소리가 번개보다 늦게 들리네"
java -jar BerkeleyParser_KorV2.jar "허리케인이 생기는 이유"
java -jar BerkeleyParser_KorV2.jar "차가 움직이는 원리"
java -jar BerkeleyParser_KorV2.jar "차가 가장 많은 나라는"
java -jar BerkeleyParser_KorV2.jar "얼음이 생기는 원리"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 더운 나라"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 추운 나라는"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 큰 새는"
java -jar BerkeleyParser_KorV2.jar "Kidsense Recognition could not understand audio, please try again and check your microphon"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 빠른 새는"
java -jar BerkeleyParser_KorV2.jar "왜 펭귄은 날 수 없나요"
java -jar BerkeleyParser_KorV2.jar "펭귄은 왜 무리지어 사나요"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 작은 동물"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 큰 고추"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 작은 고추"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 강한 곤충은"
java -jar BerkeleyParser_KorV2.jar "개미가 될 수 있는 무게는"
java -jar BerkeleyParser_KorV2.jar "사마귀 터키"
java -jar BerkeleyParser_KorV2.jar "쇠똥구리는 어떤 곤충인가요"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 긴 고추 근"
java -jar BerkeleyParser_KorV2.jar "한국에서 가장 큰 도시는"
java -jar BerkeleyParser_KorV2.jar "한국의 인구는"
java -jar BerkeleyParser_KorV2.jar "가장 인구수가 많은 나라는"
java -jar BerkeleyParser_KorV2.jar "중국의 인구수는"
java -jar BerkeleyParser_KorV2.jar "세상에서 가장 많이 쓰이는 언어는"
java -jar BerkeleyParser_KorV2.jar "판다의 주식은"
java -jar BerkeleyParser_KorV2.jar "대나무는 어떻게 자라나요"
java -jar BerkeleyParser_KorV2.jar "하마의 톡은 얼마나 되나요"
java -jar BerkeleyParser_KorV2.jar "상어의 이빨 개수는"
java -jar BerkeleyParser_KorV2.jar "늑대 인간의 실존 않아요"
java -jar BerkeleyParser_KorV2.jar "인간의 보통 달리기 속도는"
java -jar BerkeleyParser_KorV2.jar "인간의 보통 시력은"
java -jar BerkeleyParser_KorV2.jar "가장 키가 큰 인간의 이름은"
java -jar BerkeleyParser_KorV2.jar "사람은 얼마나 사나요"
java -jar BerkeleyParser_KorV2.jar "거북이의 수명은"
java -jar BerkeleyParser_KorV2.jar "커피는 어떻게 만들어지나요"
java -jar BerkeleyParser_KorV2.jar "한국의 크기"
java -jar BerkeleyParser_KorV2.jar "오로라는 어떻게 만들어지나요"
java -jar BerkeleyParser_KorV2.jar "오로라를 볼 수 있는 시기는"
